---
apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: redroid-operator
    app.kubernetes.io/part-of: redroid-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redroid-operator-controller-manager
  namespace: system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redroid-operator-controller-manager
  namespace: system
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: redroid-operator
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: redroid-operator-controller-manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: ghcr.io/isning/redroid-operator:latest
          imagePullPolicy: Always
          env:
            - name: RELATED_IMAGE_KMSG_TOOLS
              value: ghcr.io/isning/redroid-operator/kmsg-tools:latest
          command: [/manager]
          args:
            - --leader-elect
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: healthz
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
