apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redroid-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redroid-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redroid-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "redroid-operator.selectorLabels" . | nindent 8 }}
        control-plane: controller-manager
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redroid-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          image: {{ include "redroid-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [/manager]
          args:
            {{- if .Values.leaderElection }}
            - --leader-elect
            {{- end }}
            {{- if .Values.watchNamespaces.enabled }}
            - --watch-namespaces={{ join "," .Values.watchNamespaces.namespaces }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.metricsPort }}
              name: metrics
              protocol: TCP
            - containerPort: {{ .Values.healthzPort }}
              name: healthz
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.healthzPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.healthzPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
